# Generated by Django 5.2.7 on 2025-10-05 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Disponible"),
                            (2, "Ocupada"),
                            (3, "En mantenimiento"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Tipo de habitación"),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("V", "V"), ("E", "E"), ("J", "J"), ("G", "G")],
                        max_length=1,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "document_number",
                    models.PositiveIntegerField(verbose_name="Número de docuemento"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Número de teléfono"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
            ],
            options={
                "unique_together": {("document_type", "document_number")},
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField(verbose_name="Fecha de entrada")),
                ("checkout_date", models.DateField(verbose_name="Fecha de salida")),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotel_management.guest",
                        verbose_name="Huésped",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotel_management.room",
                        verbose_name="Habitación",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_management.roomtype",
                verbose_name="Tipo de habitación",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("number", "room_type")},
        ),
    ]
