# Generated by Django 5.2.7 on 2025-10-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_management", "0002_reservation_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Activa"),
        ),
    ]
